### DISCUSSION TITLE
Caddy setup?

### DISCUSSION THREAD

**Discussion by arvigeus** [inbucket/inbucket#262] [Q&A] [answered]
I am able to start the interface, but unable to receive any mails.

Here's my `docker-compose.yml`:

```yml
  inbucket:
    image: inbucket/inbucket:latest
    container_name: inbucket
    hostname: inbucket
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "2500:2500"
      - "1100:1100"
```

This is my `Caddyfile`:

```
mail.{$DOMAIN} {
	reverse_proxy inbucket:9000
	tls {
		dns hetzner {$HETZNER_API_TOKEN}
	}

	basicauth {
		# username passwd_hash
		{$BASICAUTH_USER} {$BASICAUTH_PASS}
	}
}
```

Am I missing some setting to enable mail?
