### DISCUSSION TITLE
Webhook JSON Push

### DISCUSSION THREAD

**Discussion by raynoxfr** [inbucket/inbucket#359] [Ideas]
Hello,

I have tried your project, and it's great and simple to use, not a lof of setting.
But I just have 1 idea.

I can see we can use REST API, and I have checked it, with the API REST Client, but it's not push, I have to check every time.

It's possible to add a webhook parameter to send the API JSON directly to webhook when the server receives an email, like that, I can communicate data to another app / docker container (and I can also save any data).

I don't know the GO language, but if you don't have time, I can try to edit the source code.
Can you just tell me the file, I have to edit to do it please ?

Thank you ;)

**Comment by raynoxfr** [comment]
I have something similar with python :
python3 -m aiosmtpd -d -n -l 0.0.0.0:25
Otherwise, I can do a script for that

**Comment by jhillyerd** [comment]
The current beta has Lua support, the API may change a bit before final release, but it should do what you want.  Some examples are available at https://github.com/inbucket/inbucket/wiki/Lua-Examples

This particular one makes an HTTP post when inbucket stores a message 

```
local http = require("http")
local json = require("json")

BASE_URL = "https://myapi.example.com"

function inbucket.after.message_stored(msg)
  local request = json.encode {
    subject = string.format("Mail from %q", msg.from.address),
    body = msg.subject
  }

  assert(http.post(BASE_URL .. "/notify/text", {
    headers = { ["Content-Type"] = "application/json" },
    body = request,
  }))
end
```

**Comment by raynoxfr** [comment]
Thank your for your feedback, I have tried it and It works very well ;)
But I try to get some informations, I didn't find it, I have check the API documentation, hoping to find the mail body, without success.
So I have looked for in the source code, and I have found the file "bind_message.go"  and in another file, the structure for "checkMessageMetadata" :

```
// MessageMetadata contains the basic header data for a message event.
type MessageMetadata struct {
        Mailbox string
        ID      string
        From    *mail.Address
        To      []*mail.Address
        Date    time.Time
        Subject string
        Size    int64
        Seen    bool
}
```

But I didn't find anything about the body / content of the mail.
I need this information for my webhook :/

Is it possible to get it ?
Regards 


Added :
Maybe the purpose of the feature is just to notify the webhook with the "header", in this case, I have to request the API
Like that for example :
`http://host:9000/api/v1/mailbox/test/20230410T160329-0000`

**Reply by jhillyerd** [reply]
It is not yet possible to access the body, but is something I expect to add.  You are needing just the original raw body of the email, not something that has been parsed into mime parts, correct?  If you want you can file a bug for that, otherwise I'll open one in the future.

I plan to write some docs in the future, but want the Lua API to progress further in case I make large changes, I don't want to rewrite a lot of docs.

**Reply by raynoxfr** [reply]
Doesn't matter, i can wait, i will see with my workflow automation tools to manage the response / request to API.

Of course, with parsing is better, but if necessary i can parse the raw 

I know for the documentation, it's beta version
Great job  
Thank you

**Reply by jhillyerd** [reply]
Ok, I expect I will first add methods to get the URL and raw body.  Parsed body will take a bit longer to map from enmime Parts into Lua.

For now you could consider constructing the URL from the mailbox and message ID, and "pull" the body from the webhook receiver side.

**Reply by raynoxfr** [reply]
Thank you for all

I did it, in the "inbucket.lua" :
```
local http = require("http")
local json = require("json")

WEBHOOK_HOST = os.getenv("WEBHOOK_HOST")
WEBHOOK_URL = os.getenv("WEBHOOK_URL")
REST_API = "/api/v1/mailbox/"

function inbucket.after.message_stored(msg)
  local request = json.encode {
    mailbox = msg.mailbox,
    id = msg.id,
    url = string.format("%s%s%s/%s", WEBHOOK_HOST, REST_API,  msg.mailbox, msg.id)
  }

  assert(http.post(WEBHOOK_URL, {
    headers = { ["Content-Type"] = "application/json" },
    body = request,
  }))
end
```

And of course, I define the docker compose :

```
version: '3'
services:
  smf:
    container_name: mailforwarder
    image: inbucket/inbucket:3.1.0-beta1
    environment:
      - WEBHOOK_HOST=https://email.domain.fr 
      - WEBHOOK_URL=https://webhook.site/.......... # for testing
    volumes:
      - /docker/mailforwarder/inbucket.lua:/opt/inbucket/inbucket.lua
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.email.rule=Host(`email.domain.fr`)"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.email.entrypoints=websecure"
      - "traefik.http.routers.email.tls.certresolver=myresolver"
      - "traefik.http.services.email.loadbalancer.server.port=9000"
     
    restart: unless-stopped
    ports:
      - "25:2500"
    networks:
      - traefik_proxy
      
networks: 
  traefik_proxy:
    external: true
```
